[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "apprenticeshiplearning"
authors = [
    {name = "Esteban Leiva", email = "e.leivam@uniandes.edu.co"},
]
version = "1.0.0"